name: Go
on: [ push, pull_request ]
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.18'
      - name: Run tests and generate coverage report
        run: go test -coverprofile cover.out -covermode atomic ./... ./graphviz/... ./embeddings/store/diskstore/... ./nn/approxlinear/...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./cover.out

  vet:
    name: go vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.18'
      - uses: actions/checkout@v2
      - name: go vet
        run: go vet ./... ./graphviz/... ./embeddings/store/diskstore/... ./nn/approxlinear/...

  gocyclo:
    name: gocyclo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.18'
      - name: Install gocyclo
        run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - uses: actions/checkout@v2
      - name: gocyclo
        run: gocyclo -over 15 .
