name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta2'
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta2'
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run tests and generate coverage report
      run: go test -coverprofile cover.out -covermode atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ./cover.out

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta2'
    - name: Get dependencies
      run: |
        go install golang.org/x/lint/golint@latest && \
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
    - uses: actions/checkout@v2
    - name: golint
      run: golint -set_exit_status -min_confidence 0.81 ./...
    - name: gocyclo
      run: gocyclo -ignore .pb.go -over 15 .
